# Generated by Django 5.0.4 on 2026-04-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
