# Generated by Django 5.0.4 on 2026-04-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_utente_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
