# Generated by Django 5.0.4 on 2026-04-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_utente_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='avatar',
            field=models.TextField(blank=True, default=''),
        ),
    ]
