# Generated by Django 5.0.4 on 2026-04-03 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('device_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivi',
            },
        ),
        migrations.CreateModel(
            name='Pianta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=80)),
                ('species', models.CharField(blank=True, max_length=150)),
                ('common_name', models.CharField(blank=True, max_length=150)),
                ('image', models.TextField(blank=True)),
                ('temp_min', models.FloatField(default=15)),
                ('temp_max', models.FloatField(default=30)),
                ('humidity_min', models.FloatField(default=40)),
                ('humidity_max', models.FloatField(default=70)),
                ('sunlight', models.CharField(choices=[('full sun', 'Luce diretta'), ('part shade', 'Parziale'), ('full shade', 'Ombra')], default='full sun', max_length=20)),
                ('watering', models.CharField(choices=[('frequent', 'Frequente'), ('average', 'Moderato'), ('minimum', 'Scarso'), ('none', 'Minimo')], default='average', max_length=20)),
                ('auto_irrigation', models.BooleanField(default=False)),
                ('last_temperature', models.FloatField(blank=True, null=True)),
                ('last_humidity', models.FloatField(blank=True, null=True)),
                ('last_light', models.FloatField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_irrigation', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('manual', models.BooleanField(default=False)),
                ('dispositivo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pianta', to='plants.dispositivo')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pianta',
                'verbose_name_plural': 'Piante',
            },
        ),
        migrations.CreateModel(
            name='IrrigazioneLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(default=30)),
                ('trigger', models.CharField(choices=[('manuale', 'Manuale'), ('automatica', 'Automatica')], default='manuale', max_length=20)),
                ('pianta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_logs', to='plants.pianta')),
            ],
            options={
                'verbose_name': 'Log irrigazione',
                'verbose_name_plural': 'Log irrigazioni',
                'ordering': ['-timestamp'],
            },
        ),
    ]
