# Generated by Django 5.0.4 on 2026-04-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='last_hum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='last_light',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='last_temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
