# Generated by Django 5.0.4 on 2026-04-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_dispositivo_history_dispositivo_last_hum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='last_battery',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='last_rain',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
