# Generated by Django 5.0.4 on 2026-04-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_dispositivo_last_battery_dispositivo_last_rain'),
    ]

    operations = [
        migrations.AddField(
            model_name='pianta',
            name='last_alarm_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
