# Generated by Django 6.0.1 on 2026-04-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_pianta_last_alarm_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='last_soil',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pianta',
            name='soil_max',
            field=models.FloatField(default=80),
        ),
        migrations.AddField(
            model_name='pianta',
            name='soil_min',
            field=models.FloatField(default=30),
        ),
    ]
