# Generated by Django 6.0.1 on 2026-04-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_dispositivo_last_soil_pianta_soil_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='pin',
            field=models.CharField(blank=True, help_text='Codice di 6 cifre per la registrazione', max_length=6),
        ),
    ]
