# Generated by Django 5.0.4 on 2026-04-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_dispositivo_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantCareCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=200, unique=True)),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('humidity_min', models.FloatField()),
                ('humidity_max', models.FloatField()),
                ('soil_min', models.FloatField()),
                ('soil_max', models.FloatField()),
                ('sunlight', models.CharField(max_length=20)),
                ('watering', models.CharField(max_length=20)),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cache parametri pianta',
            },
        ),
    ]
