# Generated by Django 5.0.4 on 2026-04-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_plantcarecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='pianta',
            name='last_battery',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pianta',
            name='last_soil',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
